/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dienthoai;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author abcxy
 */
public class TraThongTin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TraThongTin.class.getName());
      ArrayList<HangHoa> list= new ArrayList<>();
      HangHoa x;
    /**
     * Creates new form TraThongTin
     */
    public TraThongTin() {
        initComponents();
    }
    public void ViewTable(){
        DefaultTableModel model =(DefaultTableModel) this.tblHaha.getModel();
        model.setNumRows(0);
        int n=1;
        for(HangHoa x: list){
            if (x instanceof TelePhone){
            TelePhone tp = (TelePhone) x;
            model.addRow(new Object []{n++,tp.getMaHang(),tp.getTenHang(),"No Data",tp.getGiaNhap(),tp.getGiaBan(),tp.getGiasimghep(),tp.TinhLoiNhuan()});
        } else if(x instanceof Tablet)  {
                Tablet tb= (Tablet) x;
                model.addRow(new Object []{n++,tb.getMaHang(),tb.getTenHang(),tb.getKichthuoc(),x.getGiaNhap(),x.getGiaBan(),"No Data",x.TinhLoiNhuan()});
            }
        }
    }
     public void ReadFile(){
         try(BufferedReader br = new BufferedReader(new FileReader("hanghoa.txt"))){
             list.clear();
             String line;
             while((line=br.readLine())!=null){
                 String [] part = line.split(",");
                if(part.length==6){
                    boolean isTablet=Boolean.parseBoolean(part[0].trim());
                    String MaHang=part[1].trim();
                    String TenHang=part[2].trim();
                    int GiaNhap=Integer.parseInt(part[3].trim());
                    int GiaBan=Integer.parseInt(part[4].trim());
                    int KichThuoc=Integer.parseInt(part[5].trim());
                    Tablet tb= new Tablet(KichThuoc,isTablet,MaHang,TenHang,GiaNhap,GiaBan);
                    list.add(tb);
                }
               if(part.length==5){
                    String MaHang=part[0].trim();
                    String TenHang=part[1].trim();
                    int GiaNhap=Integer.parseInt(part[2].trim());
                    int GiaBan=Integer.parseInt(part[3].trim());
                    int Simghep=Integer.parseInt(part[4].trim());
                    TelePhone te= new TelePhone(Simghep,MaHang,TenHang,GiaNhap,GiaBan);
                    list.add(te);
               }
             }
             ViewTable();
         } catch(Exception e){
             JOptionPane.showMessageDialog(this,"Error " + e.getMessage());
         }
     }
     public void TK(){
         String name = this.txtFind.getText();
         if(name.isEmpty()){
             JOptionPane.showMessageDialog(this,"Nhap ma hang can tim");
         }
         DefaultTableModel model =(DefaultTableModel) this.tblHaha.getModel();
         int index=-1;
         for(int i=0;i<model.getRowCount();i++){
             String mh=model.getValueAt(i, 2).toString();
             if(mh.equalsIgnoreCase(name)){
                 index=i;
                 break;
             }
         }
         if(index!=-1){
             JOptionPane.showMessageDialog(this, "Found!!!");
             int viewIndex=tblHaha.convertRowIndexToView(index);
             tblHaha.setRowSelectionInterval(viewIndex, viewIndex);
             tblHaha.scrollRectToVisible(tblHaha.getCellRect(viewIndex, 0, true));
         } else {
             JOptionPane.showMessageDialog(this, "NOT FOUND "+name);
         }
     }
     public void Sort(){
         DefaultTableModel model= (DefaultTableModel) this.tblHaha.getModel();
         TableRowSorter<TableModel> sr = new TableRowSorter<>(model);
         tblHaha.setRowSorter(sr);
         sr.setSortKeys(Arrays.asList(new RowSorter.SortKey(7,SortOrder.DESCENDING)));
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHaha = new javax.swing.JTable();
        btnRead = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin hàng hóa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(444, 444, 444))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
        );

        tblHaha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã hàng", "Tên hàng", "Kích thước", "Giá nhập (USD)", "Giá bán (USD)", "Giá sim ghép (USD)", "Lợi nhuận (USD)"
            }
        ));
        jScrollPane1.setViewportView(tblHaha);

        btnRead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRead.setText("Read File");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnSort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Search:");

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRead)
                                .addGap(43, 43, 43)
                                .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRead)
                            .addComponent(btnSort))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        ReadFile();
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        // TODO add your handling code here:
        Sort();
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        TK();
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TraThongTin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHaha;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
