/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projecta;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.util.Arrays;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
/**
 *
 * @author abcxy
 */
public class Information extends javax.swing.JFrame {
    ArrayList<MatHang> list = new ArrayList<>();
    MatHang x;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Information.class.getName());

    /**
     * Creates new form Information
     */
    public Information() {
        initComponents();
    }
    public void ViewTable (){
        DefaultTableModel model= (DefaultTableModel) this.tblMenu.getModel();
        model.setNumRows(0);
        int n=1;
        for(MatHang x : list){
            model.addRow(new Object []{n++,x.getMahang(),x.getMathang(),x.getSoluong(),x.getGiavon(),x.MenhGia()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnRead = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        btnDE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Hàng", "Mặt Hàng", "Số Lượng", "Giá Vốn", "Giá Tiền"
            }
        ));
        jScrollPane1.setViewportView(tblMenu);

        btnRead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRead.setText("READ FILE");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tìm thông tin theo mã hàng: ");

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimKiem.setText("Search");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnSort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSort.setText("Increase Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        btnDE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDE.setText("Decrease Sort");
        btnDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRead)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDE, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnTimKiem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnRead)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSort)
                            .addComponent(btnDE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ReadFile(){
        try(BufferedReader br = new BufferedReader(new FileReader("mathang.txt"))){
            list.clear();
            String line;
            while ((line = br.readLine()) != null){
            String [] part = line.split(",");
            if(part.length==4){
            String Mathang=part[0].trim();
            String Mahang=part[1].trim();
            int Soluong=Integer.parseInt(part[2].trim());
            int Giavon=Integer.parseInt(part[3].trim());
            MatHang mh = new MatHang(Mathang,Mahang,Soluong,Giavon);
            list.add(mh);
            }
            if(part.length==5){
             boolean trinhdien=Boolean.parseBoolean(part[0].trim());
             String Mathang=part[1].trim();
             String Mahang=part[2].trim();
              int Soluong =Integer.parseInt(part[3].trim());
             int Giavon=Integer.parseInt(part[4].trim());
            DoUong du = new DoUong(trinhdien,Mathang,Mahang,Soluong,Giavon);
            list.add(du);
            }
        } 
            ViewTable();
                
     } catch (Exception e){
             JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
             }
        }
    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        ReadFile();
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_btnTimKiemActionPerformed
    public void Sort(){
        DefaultTableModel model=(DefaultTableModel) this.tblMenu.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(model);
        tblMenu.setRowSorter(sorter);
        sorter.toggleSortOrder(5);
        
    }
    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        // TODO add your handling code here:
        Sort();
    }//GEN-LAST:event_btnSortActionPerformed
    public void DS(){
        DefaultTableModel model=(DefaultTableModel) this.tblMenu.getModel();
        TableRowSorter<TableModel> sr = new TableRowSorter<>(model);
        tblMenu.setRowSorter(sr);
        sr.setSortKeys(Arrays.asList(new RowSorter.SortKey(5, SortOrder.DESCENDING)));
    }
    private void btnDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDEActionPerformed
        // TODO add your handling code here:
        DS();
    }//GEN-LAST:event_btnDEActionPerformed
  public void Search(){
      String name=this.txtFind.getText();
      if(name.isEmpty()){
          JOptionPane.showMessageDialog(this,"Nhap ma hang can tim");
      }
      DefaultTableModel model= (DefaultTableModel) this.tblMenu.getModel();
      int index=-1;
      for(int i=0;i<model.getRowCount();i++){
          String mh = model.getValueAt(i, 1).toString();
          if(mh.equalsIgnoreCase(name)){
              index=i;
              break;
          }
      }
      if(index!=-1){
          JOptionPane.showMessageDialog(this, "FOUND");
          int viewIndex = tblMenu.convertRowIndexToView(index);
         tblMenu.setRowSelectionInterval(viewIndex, viewIndex);
        tblMenu.scrollRectToVisible(tblMenu.getCellRect(viewIndex, 0, true));
      } else {
          JOptionPane.showMessageDialog(this,"NOT FOUND " + name);
      }
      
  }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Information().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDE;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSort;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
